import type { MoodReport } from "./types";

export const MOCK_REPORTS: MoodReport[] = [
  {
    token_mint: "ZwonkXyz...pump",
    symbol: "ZWONK",
    phase: "MEWING",
    emotion_score: 82.4,
    is_bullish: true,
    triggered_count: 4,
    headline: "Mewing. Peak emotional momentum. The wojak has transformed — but late entries carry maximum risk.",
    signals: [
      { name: "sentiment_velocity", triggered: true, score: 94.0, weight: 0.35, raw: { abs_change: 47.0 } },
      { name: "crowd_surge", triggered: true, score: 100.0, weight: 0.30, raw: { ratio: 4.6 } },
      { name: "holder_momentum", triggered: true, score: 72.0, weight: 0.20, raw: { growth_pct: 18.0 } },
      { name: "market_depth", triggered: true, score: 48.0, weight: 0.15, raw: { ratio: 14.4 } },
    ],
  },
  {
    token_mint: "FeelsXyz...pump",
    symbol: "SADGE",
    phase: "BLOOMER",
    emotion_score: 61.3,
    is_bullish: true,
    triggered_count: 3,
    headline: "Bloomer phase confirmed. Community energy is building. Emotional cycle is in motion.",
    signals: [
      { name: "sentiment_velocity", triggered: true, score: 72.0, weight: 0.35, raw: { abs_change: 36.0 } },
      { name: "crowd_surge", triggered: true, score: 78.0, weight: 0.30, raw: { ratio: 3.3 } },
      { name: "holder_momentum", triggered: true, score: 55.0, weight: 0.20, raw: { growth_pct: 13.75 } },
      { name: "market_depth", triggered: false, score: 12.0, weight: 0.15, raw: { ratio: 3.6 } },
    ],
  },
  {
    token_mint: "CopeXyz...pump",
    symbol: "COPE",
    phase: "FEELS",
    emotion_score: 37.1,
    is_bullish: false,
    triggered_count: 2,
    headline: "Early feelings stirring. The crowd is starting to notice. Not confirmed, but worth watching.",
    signals: [
      { name: "sentiment_velocity", triggered: true, score: 44.0, weight: 0.35, raw: { abs_change: 22.0 } },
      { name: "crowd_surge", triggered: false, score: 28.0, weight: 0.30, raw: { ratio: 1.1 } },
      { name: "holder_momentum", triggered: true, score: 48.0, weight: 0.20, raw: { growth_pct: 12.0 } },
      { name: "market_depth", triggered: false, score: 8.0, weight: 0.15, raw: { ratio: 2.4 } },
    ],
  },
  {
    token_mint: "NpcXyz...pump",
    symbol: "NPCOIN",
    phase: "FEELS",
    emotion_score: 27.9,
    is_bullish: false,
    triggered_count: 1,
    headline: "Early feelings stirring. The crowd is starting to notice. Not confirmed, but worth watching.",
    signals: [
      { name: "sentiment_velocity", triggered: true, score: 38.0, weight: 0.35, raw: { abs_change: 19.0 } },
      { name: "crowd_surge", triggered: false, score: 18.0, weight: 0.30, raw: { ratio: 0.7 } },
      { name: "holder_momentum", triggered: false, score: 12.0, weight: 0.20, raw: { growth_pct: 3.0 } },
      { name: "market_depth", triggered: false, score: 6.0, weight: 0.15, raw: { ratio: 1.8 } },
    ],
  },
  {
    token_mint: "GigaXyz...pump",
    symbol: "DOOMER",
    phase: "DOOMER",
    emotion_score: 9.5,
    is_bullish: false,
    triggered_count: 0,
    headline: "Token sits in the doomer zone. No emotional momentum detected. Could be accumulation — or just despair.",
    signals: [
      { name: "sentiment_velocity", triggered: false, score: 10.0, weight: 0.35, raw: { abs_change: 5.0 } },
      { name: "crowd_surge", triggered: false, score: 8.0, weight: 0.30, raw: { ratio: 0.3 } },
      { name: "holder_momentum", triggered: false, score: 5.0, weight: 0.20, raw: { growth_pct: 1.25 } },
      { name: "market_depth", triggered: false, score: 4.0, weight: 0.15, raw: { ratio: 1.2 } },
    ],
  },
  {
    token_mint: "PainXyz...pump",
    symbol: "PAIN",
    phase: "DOOMER",
    emotion_score: 3.2,
    is_bullish: false,
    triggered_count: 0,
    headline: "Token sits in the doomer zone. No emotional momentum detected. Could be accumulation — or just despair.",
    signals: [
      { name: "sentiment_velocity", triggered: false, score: 4.0, weight: 0.35, raw: { abs_change: 2.0 } },
      { name: "crowd_surge", triggered: false, score: 3.0, weight: 0.30, raw: { ratio: 0.1 } },
      { name: "holder_momentum", triggered: false, score: 2.0, weight: 0.20, raw: { growth_pct: 0.5 } },
      { name: "market_depth", triggered: false, score: 1.5, weight: 0.15, raw: { ratio: 0.45 } },
    ],
  },
];
